# Generated by Django 3.2.23 on 2026-05-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260525_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='id_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='id_proof_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='id_proof_type',
            field=models.CharField(blank=True, choices=[('AADHAAR', 'Aadhaar Card'), ('PASSPORT', 'Passport'), ('DRIVING_LICENCE', 'Driving Licence'), ('VOTER_ID', 'Voter ID Card'), ('NREGA_JOB_CARD', 'NREGA Job Card')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='pan_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected')], default='ACTIVE', max_length=20),
        ),
    ]
